import os
import csv
import shutil
import requests

# --- Configuration ---
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DOWNLOAD_DIR = os.path.join(BASE_DIR, 'openaip_downloads')
CUSTOM_DIR = os.path.join(BASE_DIR, 'input')
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')

TARGET_COUNTRIES = [
    'al', 'ad', 'am', 'at', 'az', 'by', 'be', 'ba', 'bg', 'hr', 'cy', 'cz', 
    'dk', 'ee', 'fi', 'fr', 'ge', 'de', 'gr', 'hu', 'is', 'ie', 'it', 'kz', 
    'lv', 'li', 'lt', 'lu', 'mt', 'md', 'mc', 'me', 'nl', 'mk', 'no', 'pl', 
    'pt', 'ro', 'ru', 'sm', 'rs', 'sk', 'si', 'es', 'se', 'ch', 'tr', 'ua', 
    'gb', 'uk'
]

GCS_BUCKET_ID = '29f98e10-a489-4c82-ae5e-489dbcd4912f'

# Using v1 as requested for stability
ASP_FILTERS = ["_asp_v1.txt", "_raa_v1.txt"]
CUP_FILTERS = ["_hgl.cup", "_hot.cup", "_rca.cup", "_apt.cup", "_nav.cup", "_rpp.cup"]
OBS_FILTERS = ["_obs.cup"] # Added obstacles back!

def clear_downloads():
    if os.path.exists(DOWNLOAD_DIR):
        shutil.rmtree(DOWNLOAD_DIR)
    os.makedirs(DOWNLOAD_DIR, exist_ok=True)

def fetch_openaip_data():
    print("\n--- Downloading V1 Data from OpenAIP (All Pages) ---")
    base_url = f"https://storage.googleapis.com/storage/v1/b/{GCS_BUCKET_ID}/o"
    
    # Now includes obstacles in the valid extensions
    valid_extensions = ASP_FILTERS + CUP_FILTERS + OBS_FILTERS
    page_token = None
    
    try:
        while True:
            url = base_url
            if page_token:
                url += f"?pageToken={page_token}"
                
            response = requests.get(url)
            response.raise_for_status()
            data = response.json()
            items = data.get('items', [])
            
            for item in items:
                filename = item.get('name', '').lower()
                
                is_target = any(filename.startswith(f"{c}_") for c in TARGET_COUNTRIES)
                is_valid = any(filename.endswith(ext) for ext in valid_extensions)

                if is_target and is_valid:
                    print(f"  Fetching: {filename}")
                    file_resp = requests.get(item.get('mediaLink'), stream=True)
                    if file_resp.status_code == 200:
                        with open(os.path.join(DOWNLOAD_DIR, filename), 'wb') as f:
                            for chunk in file_resp.iter_content(1024):
                                f.write(chunk)
            
            page_token = data.get('nextPageToken')
            if not page_token:
                break
                
        print("  ✅ Downloads complete for ALL countries.")
    except Exception as e:
        print(f"❌ Network Error: {e}")

def merge_text_files(file_paths, output_filename):
    path = os.path.join(OUTPUT_DIR, output_filename)
    print(f"\n--- Merging Airspaces into {output_filename} ---")
    
    with open(path, "w", encoding='utf-8', errors='ignore') as outfile:
        outfile.write("* MASTER AIRSPACE FILE\n* GENERATED BY OPENSOAR TOOLS\n\n")
        
        for fpath in sorted(file_paths):
            fname = os.path.basename(fpath)
            with open(fpath, "r", encoding='utf-8', errors='ignore') as infile:
                lines = infile.readlines()
                real_data = [l for l in lines if l.strip() and not l.strip().startswith('*')]
                
                if not real_data:
                    print(f"  ⚠️ Skipping {fname} (No data records found)")
                    continue

                print(f"  Merging: {fname}")
                outfile.write(f"\n\n* ########## START OF {fname.upper()} ##########\n")
                for line in lines:
                    outfile.write(line)
                if not lines[-1].endswith('\n'):
                    outfile.write('\n')
                outfile.write(f"* ########## END OF {fname.upper()} ##########\n\n")

def merge_cup_files(file_paths, output_filename):
    path = os.path.join(OUTPUT_DIR, output_filename)
    with open(path, "w", newline='', encoding='utf-8') as outfile:
        writer = None
        for fpath in sorted(file_paths):
            print(f"  Merging Waypoints/Obstacles: {os.path.basename(fpath)}")
            with open(fpath, "r", encoding='utf-8', errors='ignore') as infile:
                reader = csv.reader(infile)
                try:
                    header = next(reader)
                except StopIteration:
                    continue
                if writer is None:
                    writer = csv.writer(outfile)
                    writer.writerow(header)
                for row in reader:
                    # No filter here! Wind turbines are saved.
                    writer.writerow(row)

def main():
    clear_downloads()
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    fetch_openaip_data()

    # Airspace Merge
    asp_files = [os.path.join(DOWNLOAD_DIR, f) for f in os.listdir(DOWNLOAD_DIR) if any(f.endswith(e) for e in ASP_FILTERS)]
    custom_asp = os.path.join(CUSTOM_DIR, 'airspaces')
    if os.path.exists(custom_asp):
        asp_files.extend([os.path.join(custom_asp, f) for f in os.listdir(custom_asp) if f.endswith(".txt")])
    if asp_files:
        merge_text_files(asp_files, "combined_airspaces.txt")

    # Waypoint Merge
    cup_files = [os.path.join(DOWNLOAD_DIR, f) for f in os.listdir(DOWNLOAD_DIR) if any(f.endswith(e) for e in CUP_FILTERS)]
    custom_nav = os.path.join(CUSTOM_DIR, 'nav')
    if os.path.exists(custom_nav):
        cup_files.extend([os.path.join(custom_nav, f) for f in os.listdir(custom_nav) if f.endswith(".cup")])
    if cup_files:
        merge_cup_files(cup_files, "combined_airports_navaids.cup")

    # Obstacle Merge
    print("\n--- Merging Obstacles ---")
    obs_files = [os.path.join(DOWNLOAD_DIR, f) for f in os.listdir(DOWNLOAD_DIR) if any(f.endswith(e) for e in OBS_FILTERS)]
    custom_obs = os.path.join(CUSTOM_DIR, 'obstacles')
    if os.path.exists(custom_obs):
        obs_files.extend([os.path.join(custom_obs, f) for f in os.listdir(custom_obs) if f.endswith(".cup")])
    if obs_files:
        merge_cup_files(obs_files, "combined_obstacles.cup")

    print(f"\n✅ Build finished in {OUTPUT_DIR}")

if __name__ == "__main__":
    main()